import { Card } from './card.model';

export const CARDS: Card[] =
new Card("Matsu", "Normal", 1, 1, "./src/assets/images/Matsu-Normal.jpeg"),
new Card("Matsu", "Normal", 1, 2, "./src/assets/images/Matsu-Normal-2.jpeg"),
new Card("Matsu", "Ribbon", 5, 3, "./src/assets/images/Matsu-RedPoemTanzaku.jpeg"),
new Card("Matsu", "Special",20 ,4, "./src/assets/images/Matsu-Crane.jpeg"),
new Card("Ume", "Normal", 1, 5, "./src/assets/images/Ume-Normal.jpeg"),
new Card("Ume", "Normal", 1, 6, "./src/assets/images/Ume-Normal-2.jpeg"),
new Card("Ume", "Ribbon", 5, 7, "./src/assets/images/Ume-RedPoemTanzaku.jpeg"),
new Card("Ume", "Special", 10, 8, "./src/assets/images/Ume-Nightingale.jpeg"),
new Card("Sakura", "Normal", 1, 9, "./src/assets/images/Sakura-Normal.jpeg"),
new Card("Sakura", "Normal", 1, 10, "./src/assets/images/Sakura-Normal-2.jpeg"),
new Card("Sakura", "Ribbon", 5, 11, "./src/assets/images/Sakura-RedPoemTanzaku.jpeg"),
new Card("Sakura", "Special", 20, 12, "./src/assets/images/Sakura-Curtain.jpeg"),
new Card("Fuji", "Normal", 1, 13, "./src/assets/images/Fuji-Normal.jpeg"),
new Card("Fuji", "Normal", 1, 14, "./src/assets/images/Fuji-Normal-2.jpeg"),
new Card("Fuji", "Ribbon", 5, 15, "./src/assets/images/Fuji-RedTazaku.jpeg"),
new Card("Fuji", "Special", 10, 16, "./src/assets/images/Fuji-Cuckoo.jpeg"),
new Card("Ayama", "Normal", 1, 17, "./src/assets/images/Ayama-Normal.jpeg"),
new Card("Ayama", "Normal", 1, 18, "./src/assets/images/Ayama-Normal-2.jpeg"),
new Card("Ayama", "Ribbon", 5, 19, "./src/assets/images/Ayama-RedTanzaku.jpeg"),
new Card("Ayama", "Special", 10, 20, "./src/assets/images/Ayama-Bridge.jpeg"),
new Card("Botan", "Normal", 1, 21, "./src/assets/images/Botan-Normal.jpeg"),
new Card("Botan", "Normal", 1, 22, "./src/assets/images/Botan-Normal-2.jpeg"),
new Card("Botan", "Ribbon", 5, 23, "./src/assets/images/Botan-BlueTanzaku.jpeg"),
new Card("Botan", "Special", 10, 24, "./src/assets/images/Botan-Butterflies.jpeg"),
new Card("Hagi", "Normal", 1, 25,"./src/assets/images/Hagi-Normal.jpeg"),
new Card("Hagi", "Normal", 1, 26, "./src/assets/images/Hagi-Normal-2.jpeg"),
new Card("Hagi", "Ribbon", 5, 27, "./src/assets/images/Hagi-RedTanzaku.jpeg"),
new Card("Hagi", "Special", 10, 28, "./src/assets/images/Hagi-Boar.jpeg"),
new Card("Suzuki", "Normal", 1, 29, "./src/assets/images/Suzuki-Normal.jpeg"),
new Card("Suzuki", "Normal", 1, 30, "./src/assets/images/Suzuki-Normal-2.jpeg"),
new Card("Suzuki", "Special", 10, 31, "./src/assets/images/Suzuki-Geese.jpeg"),
new Card("Suzuki", "Special", 20, 32, "./src/assets/images/Suzuki-Moon.jpeg"),
new Card("Kiku", "Normal", 1, 33, "./src/assets/images/Kiku-Normal.jpeg"),
new Card("Kiku", "Normal", 1, 34, "./src/assets/images/Kiku-Normal-2.jpeg"),
new Card("Kiku", "Ribbon", 5, 35, "./src/assets/images/Kiku-BlueTanzaku.jpeg"),
new Card("Kiku", "Special", 10, 36, "./src/assets/images/Kiku-SakeCup.jpeg"),
new Card("Momiji", "Normal", 1, 37, "./src/assets/images/Momiji-Normal.jpeg"),
new Card("Momiji", "Normal", 1, 38, "./src/assets/images/Momii-Normal-2.jpeg"),
new Card("Momiji", "Ribbon", 5, 39, "./src/assets/images/Momiji-BlueTanzaku.jpeg"),
new Card("Momiji", "Special", 10, 40, "./src/assets/images/Momiji-Deer.jpeg"),
new Card("Yanagi", "Normal", 1, 41, "./src/assets/images/Yanagi-Lightning.jpeg"),
new Card("Yanagi", "Normal", 20, 42, "./src/assets/images/Yanagi-Rain.jpeg"),
new Card("Yanagi", "Ribbon", 5, 43, "./src/assets/images/Yanagi-RedTanzaku.jpeg"),
new Card("Yanagi", "Special", 10, 44, "./src/assets/images/Yanagi-Swallow.jpeg"),
new Card("Kiri", "Normal", 1, 45, "./src/assets/images/Kiri-Normal.jpeg"),
new Card("Kiri", "Normal", 1, 46, "./src/assets/images/Kiri-Normal-2.jpeg"),
new Card("Kiri", "Normal", 1, 47, "./src/assets/images/Kiri-Normal-3.jpeg"),
new Card("Kiri", "Special", 20, 48, "./src/assets/images/Kiri-Phoenix.jpeg")
];
